-- MySQL Script generated by MySQL Workbench
-- 12/31/16 10:24:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(255) NOT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  `Tipo` INT(11) NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDA` (
  `ID_VENDA` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE` INT NOT NULL DEFAULT 1,
  `VALOR_TOTAL` FLOAT NOT NULL,
  `MODALIDADE` VARCHAR(255) NOT NULL,
  `OBS` LONGTEXT NULL,
  `DATA` DATE NOT NULL,
  `USUARIO_ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_VENDA`, `USUARIO_ID_USUARIO`),
  INDEX `fk_VENDA_USUARIO1_idx` (`USUARIO_ID_USUARIO` ASC),
  CONSTRAINT `fk_VENDA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOJA` (
  `ID_LOJA` VARCHAR(1) NOT NULL,
  `LOJA` VARCHAR(255) NOT NULL,
  `ENDERECO_BANCO` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID_LOJA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITENS_DE_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITENS_DE_VENDA` (
  `ID_ITENS_DE_VENDA` INT NOT NULL AUTO_INCREMENT,
  `COD_BARRAS` VARCHAR(13) NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `VALOR_UNITARIO` DOUBLE NOT NULL,
  `LOJA_ID_LOJA` VARCHAR(1) NOT NULL,
  `VENDA_ID_VENDA` INT NOT NULL,
  PRIMARY KEY (`ID_ITENS_DE_VENDA`, `LOJA_ID_LOJA`, `VENDA_ID_VENDA`),
  INDEX `fk_ITENS_DE_VENDA_LOJA1_idx` (`LOJA_ID_LOJA` ASC),
  INDEX `fk_ITENS_DE_VENDA_VENDA1_idx` (`VENDA_ID_VENDA` ASC),
  CONSTRAINT `fk_ITENS_DE_VENDA_LOJA1`
    FOREIGN KEY (`LOJA_ID_LOJA`)
    REFERENCES `mydb`.`LOJA` (`ID_LOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITENS_DE_VENDA_VENDA1`
    FOREIGN KEY (`VENDA_ID_VENDA`)
    REFERENCES `mydb`.`VENDA` (`ID_VENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PREVENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PREVENDA` (
  `ID_PREVENDA` INT NOT NULL AUTO_INCREMENT,
  `CONTROLE` INT NOT NULL,
  `VENDA_ID_VENDAS` INT NOT NULL,
  `LOJA_ID_LOJA` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID_PREVENDA`, `VENDA_ID_VENDAS`, `LOJA_ID_LOJA`),
  INDEX `fk_PREVENDA_VENDA1_idx` (`VENDA_ID_VENDAS` ASC),
  INDEX `fk_PREVENDA_LOJA1_idx` (`LOJA_ID_LOJA` ASC),
  CONSTRAINT `fk_PREVENDA_VENDA1`
    FOREIGN KEY (`VENDA_ID_VENDAS`)
    REFERENCES `mydb`.`VENDA` (`ID_VENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PREVENDA_LOJA1`
    FOREIGN KEY (`LOJA_ID_LOJA`)
    REFERENCES `mydb`.`LOJA` (`ID_LOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = euckr;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
