//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univendas.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context_Venda : DbContext
    {
        public Context_Venda()
            : base("name=Context_Venda")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<itens_de_venda> itens_de_venda { get; set; }
        public virtual DbSet<loja> loja { get; set; }
        public virtual DbSet<prevenda> prevenda { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venda> venda { get; set; }
    }
}
