//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univendas.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context_L : DbContext
    {
        public Context_L()
            : base("name=Context_L")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TESTOQUE> TESTOQUE { get; set; }
        public virtual DbSet<TITEMPREVENDA> TITEMPREVENDA { get; set; }
        public virtual DbSet<TPREVENDA> TPREVENDA { get; set; }
    }
}
