//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univendas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCLIENTE()
        {
            this.TPREVENDA = new HashSet<TPREVENDA>();
        }
    
        public int CONTROLE { get; set; }
        public string CLIENTE { get; set; }
        public string ENDERECO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string PAIS { get; set; }
        public string CEP { get; set; }
        public string NATURALIDADE { get; set; }
        public string TIPOCLIENTE { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string IM { get; set; }
        public Nullable<System.DateTime> DATANASCIMENTO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string PAI { get; set; }
        public string MAE { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string ESTADOCIVIL { get; set; }
        public string ATIVO { get; set; }
        public string FANTASIA { get; set; }
        public string OBS { get; set; }
        public Nullable<decimal> LIMITECREDITO { get; set; }
        public string NOMECONJUGE { get; set; }
        public Nullable<System.DateTime> DATAULTIMAVENDA { get; set; }
        public Nullable<int> DIASSEMCOMPRAR { get; set; }
        public Nullable<int> CODCONVENIO { get; set; }
        public string CONVENIO { get; set; }
        public string PROFISSAO { get; set; }
        public string EMPRESAQUETRABALHA { get; set; }
        public string FONETRABALHO { get; set; }
        public Nullable<decimal> RENDAMENSAL { get; set; }
        public Nullable<decimal> TOTALVENDIDO { get; set; }
        public string NACIONALIDADE { get; set; }
        public string NUMERO { get; set; }
        public Nullable<int> CODCONSULTASPC { get; set; }
        public string SEXO { get; set; }
        public string CODIGOCIDADEIBGE { get; set; }
        public Nullable<int> CODEMITENTE { get; set; }
        public string NOMECONTATOJURIDICA { get; set; }
        public string EMAIL2 { get; set; }
        public string STATUS { get; set; }
        public string MD5L { get; set; }
        public string SERIAL { get; set; }
        public Nullable<int> CODGRUPO { get; set; }
        public string GRUPO { get; set; }
        public string FOTO { get; set; }
        public string TRIBUTACAO { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public Nullable<decimal> ISSMUNICIPIO { get; set; }
        public string DADOSADICIONAIS { get; set; }
        public string SITE { get; set; }
        public string CODIGOPAIS { get; set; }
        public string CSOSN { get; set; }
        public Nullable<decimal> PERCICMSPROPRIOST { get; set; }
        public Nullable<decimal> PERCMVAORIGINAL { get; set; }
        public Nullable<decimal> PERCICMSSTINTERNA { get; set; }
        public Nullable<decimal> PERCREDUCAOBCST { get; set; }
        public string DESCRICAOCSOSN { get; set; }
        public Nullable<int> CODIGOCSTORIGEM { get; set; }
        public string ORIGEM { get; set; }
        public string POSSUIICMSST { get; set; }
        public string ISENTO { get; set; }
        public string TRIBUTADO { get; set; }
        public Nullable<int> CODCSTORIGEM { get; set; }
        public string MENSAGEMFISCAL { get; set; }
        public Nullable<int> CODTABELAPRECO { get; set; }
        public string TABELAPRECO { get; set; }
        public Nullable<int> CODVENDEDOR { get; set; }
        public string VENDEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPREVENDA> TPREVENDA { get; set; }
    }
}
