//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univendas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTOQUE
    {
        public int CONTROLE { get; set; }
        public string PRODUTO { get; set; }
        public string TIPOBARRA { get; set; }
        public string CODBARRAS { get; set; }
        public string UNIDADE { get; set; }
        public decimal PRECOCUSTO { get; set; }
        public decimal PERCLUCRO { get; set; }
        public decimal PRECOVENDA { get; set; }
        public Nullable<int> CODGRUPO { get; set; }
        public string GRUPO { get; set; }
        public string OBS { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public string FORNECEDOR { get; set; }
        public string TAMANHO { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public Nullable<decimal> CUSTOULTIMACOMPRA { get; set; }
        public Nullable<decimal> CUSTOMEDIO { get; set; }
        public Nullable<decimal> QTDETOTALCOMPRADA { get; set; }
        public Nullable<decimal> QTDETOTALVENDIDA { get; set; }
        public Nullable<System.DateTime> DATAULTIMACOMPRA { get; set; }
        public Nullable<System.DateTime> DATAULTIMAVENDA { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<decimal> QTDEMINIMA { get; set; }
        public Nullable<decimal> QTDEMAXIMA { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public string ATIVO { get; set; }
        public string NCM { get; set; }
        public Nullable<decimal> PERCREDITOCICMS { get; set; }
        public string USAGRADE { get; set; }
        public string USASERIAL { get; set; }
        public string ORIGEM { get; set; }
        public string CODTRIBUTACAOIPI { get; set; }
        public string TRIBUTACAOIPI { get; set; }
        public string CODTRIBUTACAOPIS { get; set; }
        public string CODTRIBUTACAOCOFINS { get; set; }
        public string TRIBUTACAOPIS { get; set; }
        public string TRIBUTACAOCOFINS { get; set; }
        public string TIPOTRIBUTACAO { get; set; }
        public Nullable<decimal> PERCICMSSTINTERNA { get; set; }
        public Nullable<decimal> PERCMVAORIGINAL { get; set; }
        public string POSSUIICMSST { get; set; }
        public string ISENTO { get; set; }
        public Nullable<decimal> PERCICMSPROPRIOST { get; set; }
        public string IAT { get; set; }
        public string IPPT { get; set; }
        public string TRIBUTADO { get; set; }
        public string CSOSN { get; set; }
        public string DESCRICAOCSOSN { get; set; }
        public string PESADO { get; set; }
        public Nullable<decimal> BASECALCULOICMSSTRETIDO { get; set; }
        public Nullable<decimal> VALORICMSSTRETIDO { get; set; }
        public Nullable<decimal> ALIQUOTAICMSECF { get; set; }
        public byte[] FOTO { get; set; }
        public string MD5 { get; set; }
        public string MENSAGEMNFE { get; set; }
        public Nullable<int> CODMENSAGEMNFE { get; set; }
        public int CODUNIDADEMEDIDA { get; set; }
        public string CODAPLICACAOPRODUTO { get; set; }
        public string APLICACAOPRODUTO { get; set; }
        public string MD5E2 { get; set; }
        public Nullable<decimal> QTDEINICIAL { get; set; }
        public Nullable<decimal> ALIQUOTAISS { get; set; }
        public Nullable<int> CODIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> PERCIMPOSTOMEDIO { get; set; }
        public int CODCSTORIGEM { get; set; }
        public Nullable<int> CODIGOCSTORIGEM { get; set; }
        public Nullable<int> CODEMITENTE { get; set; }
        public Nullable<int> DIASVALIDADEPRODUTO { get; set; }
        public string FATORCONVERSAO { get; set; }
        public string TRIBUTACAOSERVICO { get; set; }
        public Nullable<decimal> REDUCAOBASECALCULOSERVICO { get; set; }
        public string STATUS { get; set; }
        public string DESCRICAOCOMPLEMENTAR { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<decimal> PRECOVENDAUSS { get; set; }
        public Nullable<decimal> PERCMAXIMODESCONTO { get; set; }
        public Nullable<decimal> VALORCOMISSAOFIXO { get; set; }
        public Nullable<decimal> PERCCOMISSAO { get; set; }
        public Nullable<decimal> PRECOMINIMOUSS { get; set; }
        public Nullable<decimal> PRECOMINIMO { get; set; }
        public Nullable<int> CODCOMPRA { get; set; }
        public Nullable<decimal> VALORFRETE { get; set; }
        public Nullable<decimal> VALOROUTROS { get; set; }
        public Nullable<decimal> VALORICMSST { get; set; }
        public Nullable<decimal> VALORIPI { get; set; }
        public Nullable<decimal> VALORUNITARIOCOMPRA { get; set; }
        public Nullable<decimal> PERCPIS { get; set; }
        public Nullable<decimal> PERCCOFINS { get; set; }
        public Nullable<decimal> VALORCONVERSAO { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public string CODIGOANP { get; set; }
        public string MARCA { get; set; }
        public Nullable<decimal> PERCREDUCAOBC { get; set; }
        public Nullable<decimal> PERCREDUCAOBCST { get; set; }
        public Nullable<int> CODSUBGRUPO { get; set; }
        public string SUBGRUPO { get; set; }
        public string CONTROLARVALIDADE { get; set; }
        public Nullable<int> CODMARCA { get; set; }
        public Nullable<decimal> PRECOREVENDA { get; set; }
        public Nullable<decimal> PERCIPI { get; set; }
        public string CFOP { get; set; }
        public string UNIDADECONVERSAOVENDA { get; set; }
        public Nullable<decimal> VALORCONVERSAOVENDA { get; set; }
        public Nullable<int> CODTABELAPRECO { get; set; }
        public string NOMETABELAPRECO { get; set; }
        public Nullable<decimal> PERCIMPOSTOMEDIOESTADUAL { get; set; }
        public Nullable<decimal> PERCIMPOSTOMEDIOMUNICIPAL { get; set; }
        public string CODIGOENQUADRAMENTOIPI { get; set; }
        public string CEST { get; set; }
        public Nullable<decimal> QTDEEMPRODUCAO { get; set; }
        public Nullable<decimal> QTDEPEDIDOVENDA { get; set; }
        public Nullable<decimal> QTDEPEDIDOCOMPRA { get; set; }
        public Nullable<decimal> QTDERESERVADA { get; set; }
        public Nullable<decimal> QTDEREAL { get; set; }
        public Nullable<decimal> QTDEEMPRODUCAOMP { get; set; }
    }
}
