//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univendas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMPREVENDA
    {
        public int CONTROLE { get; set; }
        public int CODPREVENDA { get; set; }
        public string PRODUTO { get; set; }
        public int CODPRODUTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public string UN { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string CANCELADO { get; set; }
        public string CONFIRMADO { get; set; }
        public string MESCLAR { get; set; }
    }
}
