//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersisteUnivendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens_de_venda
    {
        public int ID { get; set; }
        public int ID_ITENS_DE_VENDA { get; set; }
        public string COD_BARRAS { get; set; }
        public int QUANTIDADE { get; set; }
        public double VALOR_UNITARIO { get; set; }
        public string LOJA_ID_LOJA { get; set; }
        public int VENDA_ID_VENDA { get; set; }
    
        public virtual loja loja { get; set; }
        public virtual venda venda { get; set; }
    }
}
