//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersisteUnivendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class loja
    {
        public loja()
        {
            this.itens_de_venda = new HashSet<itens_de_venda>();
            this.prevendas = new HashSet<prevenda>();
        }
    
        public string ID_LOJA { get; set; }
        public string LOJA1 { get; set; }
        public string ENDERECO_BANCO { get; set; }
    
        public virtual ICollection<itens_de_venda> itens_de_venda { get; set; }
        public virtual ICollection<prevenda> prevendas { get; set; }
    }
}
