//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersisteUnivendas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vendaEnt : DbContext
    {
        public vendaEnt()
            : base("name=vendaEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<itens_de_venda> itens_de_venda { get; set; }
        public DbSet<loja> lojas { get; set; }
        public DbSet<prevenda> prevendas { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<venda> vendas { get; set; }
    }
}
