//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersisteUnivendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.vendas = new HashSet<venda>();
        }
    
        public int ID_USUARIO { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public int TIPO { get; set; }
    
        public virtual ICollection<venda> vendas { get; set; }
    }
}
