//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersisteUnivendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public venda()
        {
            this.itens_de_venda = new HashSet<itens_de_venda>();
            this.prevendas = new HashSet<prevenda>();
        }
    
        public int ID_VENDA { get; set; }
        public int CLIENTE { get; set; }
        public float VALOR_TOTAL { get; set; }
        public string MODALIDADE { get; set; }
        public string OBS { get; set; }
        public System.DateTime DATA { get; set; }
        public int USUARIO_ID_USUARIO { get; set; }
        public bool CANCELADO { get; set; }
    
        public virtual ICollection<itens_de_venda> itens_de_venda { get; set; }
        public virtual ICollection<prevenda> prevendas { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
